### ISSUE TITLE
Multiple users on PseudoTV / Live TV & DVR?

### ISSUE THREAD

**Issue by tetrisgm** [DEFENDORe/pseudotv#110]
I have a couple users on my Home. When we both try to play something, it requests to end the current channel to be able to start the new one. Is there any way around this? Is this a PseudoTV limitation, or a Live TV & DVR one, or just me configuring things wrong?

It looks like I'm limited by the number of tuners. Is there a way to add more?

**Comment by DEFENDORe** [comment]
Increasing the "Tuner Count" in the pseudotv settings should get this working. It's been a really long time since I looked at the code or even used the app. But ya, increasing the tuner count in the web settings should allow for multiple viewers of different channels. You may need to reconfigure your Plex/DVR app after making this change. Essentially it just lets Plex know how many streams/tuners it has available to use at any given time. Plex is smart enough not to use more than one tuner for any particular channel. So if one user is watching channel 20, and another user decided to watch channel 20, it'll only use one stream/tuner. Hope that makes sense.

In any case, I highly recommend you try out [DizqueTV](https://github.com/vexorian/dizquetv) (a fork of this project) and [ErsatzTV](https://github.com/jasongdove/ErsatzTV). This project hasn't been active in a while.
