### ISSUE TITLE
Weak end device - quesetion

### ISSUE THREAD

**Issue by gelsas** [DEFENDORe/pseudotv#36]
Is there a way to avoid as much transcoding as possible and somehow direct stream everything?

I don't think that my raspberry pi 3 I want to run this on would be strong/good enough to transcode all the streams.

Is there any solution for someone like me who wants to run this on an raspberry pi?

**Comment by powdermilkman** [comment]
The dev branch and the 0.53 release have direct stream.

**Comment by dannyvfilms** [comment]
There must be a setting I'm missing on that front, because my CPU usage is noticeably higher when a stream is active. mpeg2video is definitely better than straight H.264, but it essentially looks like a transcode is happening outside of Plex, rather than Plex just tuning into the file itself at the timecode it would have been at.

**Comment by powdermilkman** [comment]
https://github.com/DEFENDORe/pseudotv/releases/tag/v0.0.52-testing
