### ISSUE TITLE
Allow direct streaming of video/audio via ffmpeg

### ISSUE THREAD

**Issue by Wolfie713** [DEFENDORe/pseudotv#6]
Doing this would require disabling the mapping of subtitles (and thus doing a copy of any subtitle streams within the file), but could be useful.  In 0.0.4, it was possible to do this by changing the codec to "copy."  Then Plex would do any necessary transcoding vs ffmpeg.  Some people prefer to do this when possible.

**Comment by mulhearn1022** [comment]
I managed to get this mostly working in the latest version. There is a filter switch hardcoded in ffmpeg.js in the src directory that you have to comment out in order to do a stream copy (which disables the current addition of subtitles) along with a few other lines and a few changes to ffmpeg settings exposed through the UI:

lines to comment out (multiple occurences):
`//tmpArgs[vidStream] = [v]
//tmpargs.splice(vidStream - 1, 0, "-filter_complex", ...
`
error on close fix (opts.* becomes **this.**opts.*):
`this.emit('error', { code: code, cmd: `${this.opts.ffmpegPath} ${tmpargs.join(' ')}` })`

ffmpeg settings:
`-threads 4
-ss STARTTIME
-re
-fflags +genpts
-i INPUTFILE
-t DURATION
-map VIDEOSTREAM
-map 0:a?
-c:v copy
-c:a copy
-shortest
-avoid_negative_ts make_zero
-r 30
-flags cgop+ilme
-sc_threshold 1000000000
-minrate:v 10000k
-maxrate:v 10000k
-bufsize:v 1000k
-metadata service_provider="PseudoTV"
-metadata CHANNELNAME
-f mpegts
-output_ts_offset TSOFFSET
-muxdelay 0
-muxpreload 0
OUTPUTFILE`


Most of my media plays very well with this temporary workaround, but there is the rare circumstance that the video becomes super slow and jerky or no audio. I have not had time to investigate this issue further, but I think I saw one of the videos had he-aac audio -- though I'm not sure if that's part of the issue or not.

**Comment by jordankoehn** [comment]
My fork (currently on gitlab https://gitlab.com/jxordan/pseudotv-plex) handles direct streams pretty flawlessly in my testing. Need to modify the implementation to be an optional toggle then I'll make a PR.

**Comment by powdermilkman** [comment]
Jordan’s pr has been merged into development and seems to be working well for me so far. Closing issue.
